In [2]:
# The first step of using numpy is to tell python to import it
import numpy as np

### 2.1 NumPy Arrays

**NumPy Array**
* An array is a data structure that stores values of same data type.
* While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to the same data type. 
* However python lists fail to deliver the performance required while computing large sets of numerical data. To address this issue we use NumPy arrays.
* We can create NumPy arrays by converting a list to an array.

In [7]:
# defining  list of different car companies or string elements
brands_array = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

print(brands_array)

['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']


In [8]:
# defining a list of no of cylinders 
noofCylinder_array = [5, 4, 6, 7, 3]

print(noofCylinder_array)

[5, 4, 6, 7, 3]


In [13]:
# connverting the list arr_str to a NumPy array
np_brands_array = np.array(brands_array)
print("NumPy Array of Brands array is {}".format(np_brands_array))

NumPy Array of Brands array is ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']


In [11]:
# converting the list noofCylinder_array to a NumPy array
np_noofCylinder_array = np.array(noofCylinder_array)

print("NumPy Array of no of Cylinder is {}".format(np_noofCylinder_array))

NumPy Array of no of Cylinder is [5 4 6 7 3]


The resuts look similar to a list but arr_str and arr_num have been converted to NumPy arrays. Let's check the data type to confirm this.

In [14]:
print("Data Type of brands_array is {}".format(type(brands_array)))
print("Data Type of noofCylinder_array is {}".format(type(noofCylinder_array)))

print("Data Type of np_brands_array is {}".format(type(np_brands_array)))
print("Data Type of np_noofCylinder_array is {}".format(type(np_noofCylinder_array)))

Data Type of brands_array is <class 'list'>
Data Type of noofCylinder_array is <class 'list'>
Data Type of np_brands_array is <class 'numpy.ndarray'>
Data Type of np_noofCylinder_array is <class 'numpy.ndarray'>


* The above output confirms that both the lists were successfully converted to arrays

**Using np.arange() function**
* The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start is included but stop is excluded.
* It has the following paramaters:
  * start : start of interval range. By default start = 0
  * stop  : end of interval range
  * step  : step size of interval. By default step size = 1

In [3]:
array1 = np.arange(stop = 7)
print(array1)

[0 1 2 3 4 5 6]


In [4]:
array2 = np.arange(8,20)
print(array2)

[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
array3 = np.arange(8,20, 2)
print(array3)

[ 8 10 12 14 16 18]


In [6]:
array4 = np.arange(start = 20, stop = 50, step = 5)
print(array4)

[20 25 30 35 40 45]


**Using np.linspace() function**
* The np.linspace() function returns numbers which are evenly distributed with respect to interval. Here the start and stop both are included.            
* It has the following parameters:              
   * start: start of interval range. By default start = 0
   * stop: end of interval range
   * num : No. of samples to generate. By default num = 50

In [7]:
array5 = np.linspace(start = 10, stop = 20)
print(array5)
print(array5[19])

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
13.877551020408163


**How are these values getting generated?**

The step size or the difference between each element will be decided by the following formula:

**(stop - start) / (total elements - 1)**

So, in this case:
(5 - 0) / 49 = 0.10204082

The first value will be 0.10204082, the second value will be 0.10204082 + 0.10204082, the third value will be 0.10204082 + 0.10204082 +0.10204082, and so on.

In [8]:
array6 = np.linspace(start = 20, stop=40)
print(array6)

[20.         20.40816327 20.81632653 21.2244898  21.63265306 22.04081633
 22.44897959 22.85714286 23.26530612 23.67346939 24.08163265 24.48979592
 24.89795918 25.30612245 25.71428571 26.12244898 26.53061224 26.93877551
 27.34693878 27.75510204 28.16326531 28.57142857 28.97959184 29.3877551
 29.79591837 30.20408163 30.6122449  31.02040816 31.42857143 31.83673469
 32.24489796 32.65306122 33.06122449 33.46938776 33.87755102 34.28571429
 34.69387755 35.10204082 35.51020408 35.91836735 36.32653061 36.73469388
 37.14285714 37.55102041 37.95918367 38.36734694 38.7755102  39.18367347
 39.59183673 40.        ]


In [9]:
array7 = np.linspace(20, 40, 10)
print(array7)
print(array7[4])

[20.         22.22222222 24.44444444 26.66666667 28.88888889 31.11111111
 33.33333333 35.55555556 37.77777778 40.        ]
28.88888888888889


**Arithmetic Operations on arrays**

In [10]:
# arithmetic on lists

l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2)
# this is nothing but concatenation of two lists. It does not behave as you would expect!


[1, 2, 3, 4, 5, 6]


In [11]:
# we can +-*/ arrays together

# defining two arrays
arr7 = np.arange(1,6)
print('arr7:', arr7)

arr8 = np.arange(3,8)
print('arr8:', arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]


In [12]:
print('Addition: ',arr7+arr8)
print('Subtraction: ',arr7-arr8)
print('Multiplication:' , arr7*arr8)
print('Division:', arr7/arr8) # the first element of array 1 is divided by first element of array 2
print('Inverse:', 1/arr7)
print('Powers:', arr7**arr8) # in python, powers are achieved using **, NOT ^!!! ^ does something completely different!


Addition:  [ 4  6  8 10 12]
Subtraction:  [-2 -2 -2 -2 -2]
Multiplication: [ 3  8 15 24 35]
Division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1    16   243  4096 78125]


### 2.3 Accessing the entries of a Numpy Array

In [16]:
rand_num = np.random.randint(10,50)
print("rand_num - ",rand_num)
np_array1 = np.random.randint(10,100,20)
print("np_array1 -",np_array1)

rand_num -  14
np_array1 - [17 18 52 99 82 42 75 83 20 32 51 12 69 99 15 68 67 62 87 79]


In [17]:
print("First Element of the Array -", np_array1[0])

print("5th to 10th Element of the Array -", np_array1[4:10])

print("Last 5 Element of the Array -", np_array1[-5:])

print("First 5 Element of the Array -", np_array1[0:5])

First Element of the Array - 17
5th to 10th Element of the Array - [82 42 75 83 20 32]
Last 5 Element of the Array - [68 67 62 87 79]
First 5 Element of the Array - [17 18 52 99 82]


In [18]:
np_array1 > 50

array([False, False,  True,  True,  True, False,  True,  True, False,
       False,  True, False,  True,  True, False,  True,  True,  True,
        True,  True])

In [21]:
print("Array Elements greater than 50 are -", np_array1[np_array1>50])

print("Array Elements less than 30 are -", np_array1[np_array1<30])

Array Elements greater than 50 are - [52 99 82 75 83 51 69 99 68 67 62 87 79]
Array Elements less than 30 are - [17 18 20 12 15]


**Modifying the entries of an Array**

In [22]:
print(np_array1)


[17 18 52 99 82 42 75 83 20 32 51 12 69 99 15 68 67 62 87 79]


In [23]:
# let's change some values in an array!
# changing the values of index value 3 and index value 4 to 5
np_array1[3:5] = -50
print(np_array1)

[ 17  18  52 -50 -50  42  75  83  20  32  51  12  69  99  15  68  67  62
  87  79]


In [24]:
# changing the values of index value 0 and index value 1 to 2 and 3 respectively
np_array1[0:2] = [-20,-50]
print(np_array1)

[-20 -50  52 -50 -50  42  75  83  20  32  51  12  69  99  15  68  67  62
  87  79]


In [25]:
# modify entries using logical references
np_array1[np_array1>0] = 65
print(np_array1)

[-20 -50  65 -50 -50  65  65  65  65  65  65  65  65  65  65  65  65  65
  65  65]
