**NumPy Matrix**

**Using np.ones()**

* The np.ones() is another function for creating a matrix and performing matrix operations in NumPy. 
* It returns a matrix of given shape and type, filled with ones.
* It has the following parameters:  
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [ ]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
import numpy as np

* A matrix is a two-dimensional data structure where elements are arranged into rows and columns.
* A matrix can be created by using list of lists
* We see that all the NumPy objects have data type as ndarray

In [13]:
# let's say we have information of different number of cylinders in a car and we want to display them in a matrix format
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [14]:
print("Data Type of Matrix is {}".format(type(matrix)))

Data Type of Matrix is <class 'numpy.ndarray'>


In [15]:
# let's say we have information of Marks of 5 students in 5 subjects stored as list in a matrix format
subject_list = ['English','Chemistry', 'Physics', 'Computer Science', 'Maths']
student1_marks = [80, 92, 92, 92, 95]
student2_marks = [73, 88, 92, 96, 90]
student3_marks = [79, 88, 72, 66, 89]
student4_marks = [52, 62, 92, 96, 100]
student5_marks = [96, 59, 100, 72, 90]
student_mark_matrix = np.array([subject_list, student1_marks, student2_marks, student3_marks, student4_marks, student5_marks])
print(student_mark_matrix)


[['English' 'Chemistry' 'Physics' 'Computer Science' 'Maths']
 ['80' '92' '92' '92' '95']
 ['73' '88' '92' '96' '90']
 ['79' '88' '72' '66' '89']
 ['52' '62' '92' '96' '100']
 ['96' '59' '100' '72' '90']]


In [16]:
# To display a specific record or marks for a particular subject
# Print Maths Marks for All Student

def printMarksforSubject(subIndex):
    print("Marks for Subject {} is - ".format(student_mark_matrix[0][subIndex]))
    for i in range(len(subject_list)+1):
        if i != 0:
            print("Student{} is {}".format(i, student_mark_matrix[i][subIndex]))

printMarksforSubject(subIndex=4)     ## Prints Marks for Maths

Marks for Subject Maths is - 
Student1 is 95
Student2 is 90
Student3 is 89
Student4 is 100
Student5 is 90


**We can create matrices using the functions available in NumPy library**

**Using np.zeros()**
 
* The np.zeros() is a function for creating a matrix and performing matrix operations in NumPy. 
* It returns a matrix filled with zeros of the given shape. 
* It has the following parameters:    
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [17]:
matrix_zero = np.zeros([3,5])  ## Rows = 3 and Column = 5
print(matrix_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Using np.ones()**

* The np.ones() is another function for creating a matrix and performing matrix operations in NumPy. 
* It returns a matrix of given shape and type, filled with ones.
* It has the following parameters:  
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [18]:
matrix_one = np.ones([5,3])
print(matrix_one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Using np.eye()**
* The np.eye() is a function for creating a matrix and performing matrix operations in NumPy. 
* It returns a matrix with ones on the diagonal and zeros elsewhere. 
* It has the following parameters:
  * n: Number of rows and columns in the output matrix 
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [19]:
matrix_eye = np.eye(5)
print(matrix_eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
matrix_eye2 = np.eye(2,3)
print(matrix_eye2)

[[1. 0. 0.]
 [0. 1. 0.]]


In [20]:
matrix_eye3 = np.eye(5,5)
print(matrix_eye3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
matrix_eye4 = np.eye(5,3)
print(matrix_eye4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


**We can also convert a one dimension array to a matrix. This can be done by using the np.reshape() function.**

* The shape of an array basically tells the number of elements and dimensions of the array. Reshaping a Numpy array simply means changing the shape of the given array. 
* By reshaping an array we can add or remove dimensions or change number of elements in each dimension. 
* In order to reshape a NumPy array, we use the reshape method with the given array. 
* **Syntax:** array.reshape(shape) 
  * shape: a tuple given as input, the values in tuple will be the new shape of the array.

In [23]:
array2 = np.arange(8,20)
print(array2)

[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
array4 = np.arange(start = 20, stop = 50, step = 5)
print(array4)

[20 25 30 35 40 45]


In [25]:
array2_matrix = np.reshape(array2,(3,4))
print(array2_matrix)

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [26]:
array2_matrix_02 = array2.reshape(4,3)
print(array2_matrix_02)

[[ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [28]:
array2_matrix_03 = array2.reshape(4,4)
print(array2_matrix_03)

ValueError: cannot reshape array of size 12 into shape (4,4)

* This did not work because we have 10 elements which we are trying to fit in a 2 X 6 shape which will require 12 elements.

**Operations on Matrices**

In [29]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
# the first element of array 1 is operated along withv first element of array 2

print('Addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8)
print('Division: \n', matrix7/matrix8)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\Sudhanshu\AppData\Local\Temp\ipykernel_7908\2604038799.py:4: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8)


* RuntimeWarning: Errors which occur during program execution(run-time) after successful compilation are called run-time errors. 
* One of the most common run-time error is division by zero also known as Division error. 
* Due to division by zero error, we are getting inf (infinity) values because 1/0 is not a defined operation.

**Linear algebra matrix multiplication**

In [31]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('')
# taking linear algebra matrix multiplication (some may have heard this called the dot product)
print('Multiplication: \n', matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


**Transpose of a matrix**

In [32]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# taking transpose of matrix
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
# another way of taking a transpose
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Function to find minimum and maximum values**

In [35]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print('Minimum value: ',np.min(matrix9))

Minimum value:  1


In [37]:
print('Maximum value: ',np.max(matrix9))

Maximum value:  9


### 2.3 Accessing the entries of a Numpy Array - Matrix

In [39]:
rand_num = np.random.randint(10,50)
print("rand_num - ",rand_num)

np_array1 = np.random.randint(10,100,20)
print("np_array1 -",np_array1)

np_matrix1 = np.random.randint(10,200,[6,6])
print("np_matrix1 -\n",np_matrix1)

rand_num -  32
np_array1 - [36 28 61 68 68 46 31 13 92 86 83 57 87 95 20 41 66 45 66 13]
np_matrix1 -
 [[ 97 148 164  95  11  80]
 [161  83  74  43  66  59]
 [ 70 133 127 197  31  73]
 [ 74 186 178  68  20  31]
 [109  73 138  47 133  92]
 [ 13  43  76 131 149  90]]


In [46]:
print("First Element of the Array -", np_array1[0])

print("5th to 10th Element of the Array -", np_array1[4:10])

print("Last 5 Element of the Array -", np_array1[-5:])

print("First 5 Element of the Array -", np_array1[0:5])


print("First row of the Matrix -", np_matrix1[0])
print("First column of the Matrix -", np_matrix1[: ,0])

print("Last row of the Matrix -", np_matrix1[-1])
print("Last column of the Matrix -", np_matrix1[: ,-1])

# "acessing third element of the second row", acessing third element of the second row
print("Acessing third element of the second row", np_matrix1[1][2])
#or 
print("Acessing third element of the second row",np_matrix1[1,2])
 
print("Accessing first two rows with second and third column - \n",np_matrix1[0:2,1:3])

First Element of the Array - 36
5th to 10th Element of the Array - [68 46 31 13 92 86]
Last 5 Element of the Array - [41 66 45 66 13]
First 5 Element of the Array - [36 28 61 68 68]
First row of the Matrix - [ 97 148 164  95  11  80]
First column of the Matrix - [ 97 161  70  74 109  13]
Last row of the Matrix - [ 13  43  76 131 149  90]
Last column of the Matrix - [80 59 73 31 92 90]
Acessing third element of the second row 74
Acessing third element of the second row 74
Accessing first two rows with second and third column - 
 [[148 164]
 [ 83  74]]


In [47]:
print("Array Elements greater than 50 are -", np_array1[np_array1>50])

print("Array Elements less than 30 are -", np_array1[np_array1<30])

print("Matrix Elements greater than 50 are -", np_matrix1[np_matrix1>100])

print("Matrix Elements less than 30 are -", np_matrix1[np_matrix1<50])

Array Elements greater than 50 are - [61 68 68 92 86 83 57 87 95 66 66]
Array Elements less than 30 are - [28 13 20 13]
Matrix Elements greater than 50 are - [148 164 161 133 127 197 186 178 109 138 133 131 149]
Matrix Elements less than 30 are - [11 43 31 20 31 47 13 43]


**Modifying the entries of a Matrix**

In [48]:
print(np_matrix1)

[[ 97 148 164  95  11  80]
 [161  83  74  43  66  59]
 [ 70 133 127 197  31  73]
 [ 74 186 178  68  20  31]
 [109  73 138  47 133  92]
 [ 13  43  76 131 149  90]]


In [51]:
# changing the values of the 4th and 5th element of the second and third rows of the matrix to 0
print('Matrix before modification: \n',np_matrix1)
np_matrix1[0:3,2:5] = -50
print('\n Matrix after modification: \n',np_matrix1)

Matrix before modification: 
 [[ 97 148 164  95  11  80]
 [161  83  74 -50 -50  59]
 [ 70 133 127 -50 -50  73]
 [ 74 186 178  68  20  31]
 [109  73 138  47 133  92]
 [ 13  43  76 131 149  90]]

 Matrix after modification: 
 [[ 97 148 -50 -50 -50  80]
 [161  83 -50 -50 -50  59]
 [ 70 133 -50 -50 -50  73]
 [ 74 186 178  68  20  31]
 [109  73 138  47 133  92]
 [ 13  43  76 131 149  90]]


In [52]:
# extracting the first 2 rows and first 3 columns from the matrix
sub_matrix = np_matrix1[1:4,2:5]
print(sub_matrix)

[[-50 -50 -50]
 [-50 -50 -50]
 [178  68  20]]


In [53]:
# changing all the values of the extracted matrix to 3
sub_matrix[:] = 1
print(sub_matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [54]:
# what happened to rand_mat when we change sub_mat?
print(np_matrix1)

[[ 97 148 -50 -50 -50  80]
 [161  83   1   1   1  59]
 [ 70 133   1   1   1  73]
 [ 74 186   1   1   1  31]
 [109  73 138  47 133  92]
 [ 13  43  76 131 149  90]]


In [55]:
# to prevent this behavior we need to use the .copy() method when we assign sub_mat
# this behavior is the source of MANY errors for early python users!!!

np_matrix2 = np.random.randint(10,200,[6,6])
print(np_matrix2)
print("\n")
sub_matrix2 = np_matrix2[1:4,2:5].copy()
sub_matrix2[:] = 1
print(sub_matrix2)
print("\n")
print(np_matrix2)

[[114 174  41  24  11  49]
 [ 74 132  11 184  78 106]
 [177 147 176 189 134  66]
 [ 36 128  64  65  74 112]
 [ 85  32 184  49  22 150]
 [197  86 176  19  47  73]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


[[114 174  41  24  11  49]
 [ 74 132  11 184  78 106]
 [177 147 176 189 134  66]
 [ 36 128  64  65  74 112]
 [ 85  32 184  49  22 150]
 [197  86 176  19  47  73]]
