**NumPy Matrix**

In [6]:
import numpy as np

* A matrix is a two-dimensional data structure where elements are arranged into rows and columns.
* A matrix can be created by using list of lists
* We see that all the NumPy objects have data type as ndarray

In [7]:
# let's say we have information of different number of cylinders in a car and we want to display them in a matrix format
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [11]:
print("Data Type of Matrix is {}".format(type(matrix)))

Data Type of Matrix is <class 'numpy.ndarray'>


In [13]:
# let's say we have information of Marks of 5 students in 5 subjects stored as list in a matrix format
subject_list = ['English','Chemistry', 'Physics', 'Computer Science', 'Maths']
student1_marks = [80, 92, 92, 92, 95]
student2_marks = [73, 88, 92, 96, 90]
student3_marks = [79, 88, 72, 66, 89]
student4_marks = [52, 62, 92, 96, 100]
student5_marks = [96, 59, 100, 72, 90]
student_mark_matrix = np.array([subject_list, student1_marks, student2_marks, student3_marks, student4_marks, student5_marks])
print(student_mark_matrix)


[['English' 'Chemistry' 'Physics' 'Computer Science' 'Maths']
 ['80' '92' '92' '92' '95']
 ['73' '88' '92' '96' '90']
 ['79' '88' '72' '66' '89']
 ['52' '62' '92' '96' '100']
 ['96' '59' '100' '72' '90']]


In [32]:
# To display a specific record or marks for a particular subject
# Print Maths Marks for All Student

def printMarksforSubject(subIndex):
    print("Marks for Subject {} is - ".format(student_mark_matrix[0][subIndex]))
    for i in range(len(subject_list)+1):
        if i != 0:
            print("Student{} is {}".format(i, student_mark_matrix[i][subIndex]))

printMarksforSubject(subIndex=4)     ## Prints Marks for Maths

Marks for Subject Maths is - 
Student1 is 95
Student2 is 90
Student3 is 89
Student4 is 100
Student5 is 90
