### 2.2 NumPy Functions

In [9]:
import numpy as np

**There are different ways to create NumPy arrays using the functions available in NumPy library**

**Using np.arange() function**
* The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start is included but stop is excluded.
* It has the following paramaters:
  * start : start of interval range. By default start = 0
  * stop  : end of interval range
  * step  : step size of interval. By default step size = 1

In [10]:
array1 = np.arange(stop = 7)
print(array1)

[0 1 2 3 4 5 6]


In [11]:
array2 = np.arange(8,20)
print(array2)

[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
array3 = np.arange(8,20, 2)
print(array3)

[ 8 10 12 14 16 18]


In [13]:
array4 = np.arange(start = 20, stop = 50, step = 5)
print(array4)

[20 25 30 35 40 45]


**Using np.linspace() function**
* The np.linspace() function returns numbers which are evenly distributed with respect to interval. Here the start and stop both are included.            
* It has the following parameters:              
   * start: start of interval range. By default start = 0
   * stop: end of interval range
   * num : No. of samples to generate. By default num = 50

In [14]:
array5 = np.linspace(start = 10, stop = 20)
print(array5)
print(array5[19])

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
13.877551020408163


**How are these values getting generated?**

The step size or the difference between each element will be decided by the following formula:

**(stop - start) / (total elements - 1)**

So, in this case:
(5 - 0) / 49 = 0.10204082

The first value will be 0.10204082, the second value will be 0.10204082 + 0.10204082, the third value will be 0.10204082 + 0.10204082 +0.10204082, and so on.

In [15]:
array6 = np.linspace(start = 20, stop=40)
print(array6)

[20.         20.40816327 20.81632653 21.2244898  21.63265306 22.04081633
 22.44897959 22.85714286 23.26530612 23.67346939 24.08163265 24.48979592
 24.89795918 25.30612245 25.71428571 26.12244898 26.53061224 26.93877551
 27.34693878 27.75510204 28.16326531 28.57142857 28.97959184 29.3877551
 29.79591837 30.20408163 30.6122449  31.02040816 31.42857143 31.83673469
 32.24489796 32.65306122 33.06122449 33.46938776 33.87755102 34.28571429
 34.69387755 35.10204082 35.51020408 35.91836735 36.32653061 36.73469388
 37.14285714 37.55102041 37.95918367 38.36734694 38.7755102  39.18367347
 39.59183673 40.        ]


In [16]:
array7 = np.linspace(20, 40, 10)
print(array7)
print(array7[4])

[20.         22.22222222 24.44444444 26.66666667 28.88888889 31.11111111
 33.33333333 35.55555556 37.77777778 40.        ]
28.88888888888889


**We can also convert a one dimension array to a matrix. This can be done by using the np.reshape() function.**

* The shape of an array basically tells the number of elements and dimensions of the array. Reshaping a Numpy array simply means changing the shape of the given array. 
* By reshaping an array we can add or remove dimensions or change number of elements in each dimension. 
* In order to reshape a NumPy array, we use the reshape method with the given array. 
* **Syntax:** array.reshape(shape) 
  * shape: a tuple given as input, the values in tuple will be the new shape of the array.

In [17]:
array2 = np.arange(8,20)
print(array2)

[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
array4 = np.arange(start = 20, stop = 50, step = 5)
print(array4)

[20 25 30 35 40 45]


In [19]:
array2_matrix = np.reshape(array2,(3,4))
print(array2_matrix)

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [20]:
array2_matrix_02 = array2.reshape(4,3)
print(array2_matrix_02)

[[ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [21]:
array2_matrix_03 = array2.reshape(4,4)
print(array2_matrix_03)

ValueError: cannot reshape array of size 12 into shape (4,4)

**NumPy can also perform a large number of different mathematical operations and it provides different functions to do so.**

NumPy provides:
1. Trigonometric functions 
2. Exponents and Logarithmic functions
3. Functions for arithmetic operations between arrays and matrices

In [8]:
print('Sine Function:',np.sin(10))
print('Cosine Function:',np.cos(10))
print('Tan Function',np.tan(10))

Sine Function: -0.9880316240928618
Cosine Function: 0.15425144988758405
Tan Function -6.405331196646276


**Exponents and Logarithmic functions**

* Exponents

In [22]:
np.exp(10)

22026.465794806718

In [24]:
np.exp(2)

7.38905609893065

In [27]:
arr5 = np.array([2,4,6])
print(arr5)

print("Exponents of arr5 is ", np.exp(arr5))

[2 4 6]
Exponents of arr5 is  [  7.3890561   54.59815003 403.42879349]


* Logarithms

In [28]:
# by default NumPy takes the base of log as e
np.log(2)

0.6931471805599453

In [31]:
arr6 = np.array([2,4,6])
print(arr6)
print("Logarithms of arr6 to base e is ",np.log(arr6))
print("Logarithms of arr6 to base 10 is ",np.log10(arr6))

[2 4 6]
Logarithms of arr6 to base e is  [0.69314718 1.38629436 1.79175947]
Logarithms of arr6 to base 10 is  [0.30103    0.60205999 0.77815125]


**Function to generate random samples**

**Using np.random.rand function**

* The np.random.rand returns a random NumPy array whose element(s) are drawn randomly from the normal distribution over [0,1). (including 0 but excluding 1). 
* **Syntax** - np.random.rand(d0,d1)
  * d0,d1 – It represents the dimension of the required array given as int, where d1 is optional. 

In [32]:
# Generating random values in an array
rand_array = np.random.rand(10)
print(rand_array)

[0.73660768 0.63903862 0.21193592 0.44597846 0.36480392 0.24921215
 0.35000254 0.95124356 0.11909071 0.86488384]


In [36]:
# * Generating random values in a matrix
rand_array2 = np.random.rand(6, 6)
print(rand_array2)

[[0.0566908  0.93710717 0.26374046 0.86099482 0.5061807  0.96030873]
 [0.32574926 0.72265707 0.32050932 0.31855027 0.52447473 0.12590384]
 [0.26266742 0.46193455 0.17044056 0.47503133 0.70870495 0.80011583]
 [0.77096142 0.10657053 0.6018569  0.21419901 0.13946807 0.2728971 ]
 [0.08392987 0.98228508 0.99829007 0.61111536 0.88633142 0.25979521]
 [0.36142872 0.93030472 0.35814791 0.40975135 0.04404852 0.25105157]]


**Using np.random.randn function**

* The np.random.randn returns a random numpy array whose sample(s) are drawn randomly from the standard normal distribution (Mean as 0 and standard deviation as 1)

* **Syntax** - np.random.randn(d0,d1)
  * d0,d1 – It represents the dimension of the output, where d1 is optional.

In [38]:
# Generating random values in an array
rand_array4 = np.random.randn(5) 
print(rand_array4)

[-0.63807616 -1.65364591  0.22856689  0.34841645  0.77194455]


In [39]:
# Generating random values in a matrix
rand_matrix2 = np.random.randn(3,3) 
print(rand_matrix2)

[[-0.15107842  0.47055578 -0.11081409]
 [-0.2932376  -1.16430485  1.21070503]
 [ 0.03864132 -0.05392077 -0.14379292]]


In [40]:
# Let's check the mean and standard deviation of rand_mat2
print('Mean:',np.mean(rand_matrix2))
print('Standard Deviation:',np.std(rand_matrix2))

Mean: -0.02191628070572575
Standard Deviation: 0.59485591378003


*  We observe that the mean is very close to 0 and standard deviation is very close to 1.

**Using np.random.randint function**

* The np.random.randint returns a random numpy array whose element(s) are drawn randomly from low (inclusive) to the high (exclusive) range. 

* **Syntax** - np.random.randint(low, high, size) 

  * low – It represents the lowest inclusive bound of the distribution from where the sample can be drawn.
  * high – It represents the upper exclusive bound of the distribution from where the sample can be drawn. 
  * size – It represents the shape of the output. 

In [43]:
# Generating random integer values in an array
rand_array3 = np.random.randint(1,5,10)
print(rand_array3)

[1 3 3 3 3 2 4 2 1 3]


In [44]:
# Generating random integer values in a matrix
rand_matrix3 = np.random.randint(1,50,[6,6])
print(rand_matrix3)

[[46  1 22 44 33 34]
 [ 3  9 13 48 42 19]
 [30  2  8  2 40 12]
 [41 19 34 44 42 10]
 [49 24 49 21  4 44]
 [37 45  6 11 49 48]]
