### 2.4 Saving and Loading a NumPy array

**Let's save some NumPy objects on the disk for use later!**

In [2]:
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
# creating a random matrices
randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix1)
print('')
randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)

[[5 5 8 8 5]
 [2 1 1 6 8]]

[[14 18 15 14 17]
 [16 10 12 12 11]]


**Using np.save() function**

In [5]:
np.save('/content/drive/MyDrive/Python-for-DSBA/random-matrix',randint_matrix1)

**Using np.savez() function**

In [6]:
np.savez('/content/drive/MyDrive/Python-for-DSBA/random-matrix-multiple_files',randint_matrix1=randint_matrix1,randint_matrix2=randint_matrix2)

* The files will be saved in the directory where the Jupyter Notebook is located.
* With np.save() function, we can save an array/matrix to a NumPy .npy format.
* np.savez() function has an advantage over np.save() function because with np.savez(), we can store several arrays/matrices into a single file in uncompressed .npz format.

In [7]:
# now let's load it
loaded_arr = np.load('/content/drive/MyDrive/Python-for-DSBA/random-matrix.npy')
loaded_multi = np.load('/content/drive/MyDrive/Python-for-DSBA/random-matrix-multiple_files.npz')

print(loaded_arr)
print('')
print(loaded_multi)

[[5 5 8 8 5]
 [2 1 1 6 8]]



* We see that .npy file has been loaded but the .npz file is returning a memory location.
* Let's see how to load the values stored in .npz file.

In [8]:
print('1st Matrix: \n',loaded_multi['randint_matrix1'])
print('2nd Matrix: \n',loaded_multi['randint_matrix2'])

new_matrix  = loaded_multi['randint_matrix1']
print('New Matrix: \n',new_matrix)

1st Matrix: 
 [[5 5 8 8 5]
 [2 1 1 6 8]]
2nd Matrix: 
 [[14 18 15 14 17]
 [16 10 12 12 11]]
New Matrix: 
 [[5 5 8 8 5]
 [2 1 1 6 8]]


In [9]:
# we can also save/load text files...but only single variables
np.savetxt('/content/drive/MyDrive/Python-for-DSBA/random-matrix-output.txt',randint_matrix1,delimiter=',')
rand_mat_txt = np.loadtxt('/content/drive/MyDrive/Python-for-DSBA/random-matrix-output.txt',delimiter=',')
print(randint_matrix1)
print('')
print(rand_mat_txt)

[[5 5 8 8 5]
 [2 1 1 6 8]]

[[5. 5. 8. 8. 5.]
 [2. 1. 1. 6. 8.]]
