### 2.4 Saving and Loading a NumPy array

**Let's save some NumPy objects on the disk for use later!**

In [1]:
import numpy as np

In [2]:
# creating a random matrices
randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix1)
print('')
randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)

[[1 6 7 9 7]
 [8 5 2 6 2]]

[[10 13 15 17 10]
 [10 10 18 17 19]]


**Using np.save() function**

In [4]:
## C:\Users\Sudhanshu\gitrepository\dsba-python-basic-preparation\python-numpy-examples\
np.save('random-matrix',randint_matrix1)

**Using np.savez() function**

In [5]:
np.savez('random-matrix-multiple_files',randint_matrix1=randint_matrix1,randint_matrix2=randint_matrix2)

* The files will be saved in the directory where the Jupyter Notebook is located.
* With np.save() function, we can save an array/matrix to a NumPy .npy format.
* np.savez() function has an advantage over np.save() function because with np.savez(), we can store several arrays/matrices into a single file in uncompressed .npz format.

In [6]:
# now let's load it
loaded_arr = np.load('random-matrix.npy')
loaded_multi = np.load('random-matrix-multiple_files.npz')

print(loaded_arr)
print('')
print(loaded_multi)

[[1 6 7 9 7]
 [8 5 2 6 2]]



* We see that .npy file has been loaded but the .npz file is returning a memory location.
* Let's see how to load the values stored in .npz file.

In [7]:
print('1st Matrix: \n',loaded_multi['randint_matrix1'])
print('2nd Matrix: \n',loaded_multi['randint_matrix2'])

new_matrix  = loaded_multi['randint_matrix1']
print('New Matrix: \n',new_matrix)

1st Matrix: 
 [[1 6 7 9 7]
 [8 5 2 6 2]]
2nd Matrix: 
 [[10 13 15 17 10]
 [10 10 18 17 19]]
New Matrix: 
 [[1 6 7 9 7]
 [8 5 2 6 2]]


In [8]:
# we can also save/load text files...but only single variables
np.savetxt('random-matrix-output.txt',randint_matrix1,delimiter=',')
rand_mat_txt = np.loadtxt('random-matrix-output.txt',delimiter=',')
print(randint_matrix1)
print('')
print(rand_mat_txt)

[[1 6 7 9 7]
 [8 5 2 6 2]]

[[1. 6. 7. 9. 7.]
 [8. 5. 2. 6. 2.]]
