In [4]:
import numpy as np

n1 = np.array([1,2,3,4,5,6,7,8,9])
print(n1)
n1

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(n1)

numpy.ndarray

In [12]:
n2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(n2)
type(n2)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


numpy.ndarray

In [15]:
n3 = np.zeros((2,3))
print(n3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
n4 = np.zeros((6,5))
print(n4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
n5 = np.full((2,6),29)
print(n5)

[[29 29 29 29 29 29]
 [29 29 29 29 29 29]]


In [21]:
n5b = np.full((2,6),0)
print(n5b)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [22]:
n6 = np.arange(10,20)
print(n6)

[10 11 12 13 14 15 16 17 18 19]


In [23]:
n7 = np.arange(10,50,5)   ## 5 is skip value
print(n7)

[10 15 20 25 30 35 40 45]


In [28]:
n8 = np.random.randint(10,100,5)  ## To get 5 random integers from 1 to 100
print(n8)

[74 28 11 62 41]


In [32]:
n9 = np.array([[10,20,30,40],[40,30,20,10]])
print(n9)
print(n9.shape)
#n9.shape = (3,2)## cannot reshape array of size 8 into shape (3,2)
#print(n9)
#print(n9.shape)
n9.shape = (4,2)
print(n9)
print(n9.shape)


[[10 20 30 40]
 [40 30 20 10]]
(2, 4)
[[10 20]
 [30 40]
 [40 30]
 [20 10]]
(4, 2)
