In [8]:
import numpy as np
n1 = np.array([10,12,14,16,18,20])
n2 = np.array([100,200,300,400,500,600])
np.vstack((n1,n2))

array([[ 10,  12,  14,  16,  18,  20],
       [100, 200, 300, 400, 500, 600]])

In [15]:
np.vstack((n2,n1))
vfinal = np.vstack((n2,n1))
print(vfinal)

[[100 200 300 400 500 600]
 [ 10  12  14  16  18  20]]


In [10]:
import numpy as np
n1 = np.array([10,12,14,16,18,20])
n2 = np.array([100,200,300,400,500,600])
np.hstack((n1,n2))

array([ 10,  12,  14,  16,  18,  20, 100, 200, 300, 400, 500, 600])

In [14]:
np.hstack((n2,n1))
print(np.hstack((n2,n1)))
hfinal = np.hstack((n2,n1))
print("hfinal -",hfinal)

[100 200 300 400 500 600  10  12  14  16  18  20]
hfinal - [100 200 300 400 500 600  10  12  14  16  18  20]


In [17]:
import numpy as np
n1 = np.array([10,12,14,16,18,20])
n2 = np.array([100,200,300,400,500,600])
cfinal = np.column_stack((n1,n2))
print(cfinal)

[[ 10 100]
 [ 12 200]
 [ 14 300]
 [ 16 400]
 [ 18 500]
 [ 20 600]]
