In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import os

In [4]:
os.getcwd()

'C:\\Users\\Sudhanshu\\gitrepository\\dsba-python-basic-preparation\\W2-PracticeSession\\Quiz'

In [10]:
Names=[1,"Michael", 2 , "Rocky",3, "James", "4", "Johnus"]
Age = [1,2,3,4]
np_arr_Names = np.array(Names)
np_arr_Age = np.array(Age)
print(np_arr_Names)
print(np_arr_Age)
print(type(np_arr_Names))
print(type(np_arr_Age))

['1' 'Michael' '2' 'Rocky' '3' 'James' '4' 'Johnus']
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
arr1 = np.arange(0,1)
print(arr1)

arr2 = np.linspace(0,1)
print(arr2)

[0]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [13]:
np_array=np.arange(13,31)
print(np_array)

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [16]:
np_array_reshape=np_array.reshape([3,6])
print(np_array_reshape)
np_array_reshape

[[13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [24]:
matA=[[0.63210023, 0.99338139, 0.16793459],
 [0.67031607, 0.8320512, 0.51020623],
 [0.55752543, 0.29201488, 0.19119979]]

matB=[[0.24025984, 0.13609811, 0.82123344],
 [0.86363248, 0.07512739, 0.40111316],
 [0.00925655, 0.33532159, 0.87477532]]

np_matA=np.array(matA)
np_matB=np.array(matB)
print(np_matA)
print(np_matB)

matC=np_matA@np_matB
print(matC)

[[0.63210023 0.99338139 0.16793459]
 [0.67031607 0.8320512  0.51020623]
 [0.55752543 0.29201488 0.19119979]]
[[0.24025984 0.13609811 0.82123344]
 [0.86363248 0.07512739 0.40111316]
 [0.00925655 0.33532159 0.87477532]]
[[1.01133923 0.21696989 1.06446523]
 [0.88435922 0.32482175 1.33054848]
 [0.38791436 0.16192989 0.7422464 ]]


In [25]:
print(matC.min())
print(matC.max())

0.1619298906659666
1.3305484762814164


In [35]:
df = pd.read_csv('University.csv',dayfirst=True)

In [36]:
df.head()

University Student_Name  Grades Fees(Overall)  \
0                     Harvard University.       Stuart     8.0        $80000   
1  Massachusetts Institute of Technology.    Rosemarry     9.0        $75000   
2                    Stanford University.     Flamingo     9.5        $67770   
3                University of California        Kiara     8.0        $77000   
4     The University of Oxford in Oxford.       Oliver     7.5        $95000   

       Hobbies Date_of_Admission  
0     Painting        08-02-2022  
1      Driving        11-02-2022  
2  Photography        12-02-2022  
3   Travelling        13-11-2021  
4   Travelling        14-11-2021

In [38]:
df['Date_of_Admission'] = pd.to_datetime(df['Date_of_Admission'],dayfirst=True)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   University         9 non-null      object        
 1   Student_Name       9 non-null      object        
 2   Grades             9 non-null      float64       
 3   Fees(Overall)      9 non-null      object        
 4   Hobbies            9 non-null      object        
 5   Date_of_Admission  9 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 560.0+ bytes


In [41]:
Month = df['Date_of_Admission'].dt.month
print(Month)

0     2
1     2
2     2
3    11
4    11
5    11
6    11
7     2
8     2
Name: Date_of_Admission, dtype: int64


In [42]:
array_1 = np.linspace(0,20,6)
array_2 = np.arange(0,20,6)

print(array_1)

print(array_2)

[ 0.  4.  8. 12. 16. 20.]
[ 0  6 12 18]


In [43]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256], 
                [ 49, 64, 81, 289, 324, 361]])

mat.mean()

131.66666666666666

In [44]:
np.cos([0, 1, 2, 3, 4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [45]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [47]:
mat[1] = 5

In [48]:
mat[1]

array([5, 5, 5])

In [49]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21


In [50]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [51]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])

In [52]:
n1@n2

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [53]:
df_books = pd.read_csv('books.csv')

In [54]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               5000 non-null   object 
 1   author              5000 non-null   object 
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   float64
 4   language_code       4923 non-null   object 
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64  
 7   text_reviews_count  5000 non-null   int64  
 8   publisher           5000 non-null   object 
 9   year                5000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 390.8+ KB


In [55]:
df_books.shape

(5000, 10)

In [57]:
df_books.describe().T

count          mean           std           min  \
average_rating      5000.0  3.931932e+00  3.487415e-01  0.000000e+00   
isbn13              5000.0  9.752757e+12  5.129254e+11  8.987060e+09   
num_pages           4967.0  3.410940e+02  2.309861e+02  1.000000e+00   
ratings_count       5000.0  2.017549e+04  1.175026e+05  0.000000e+00   
text_reviews_count  5000.0  5.926886e+02  2.539539e+03  0.000000e+00   
year                5000.0  2.000132e+03  8.069043e+00  1.913000e+03   

                             25%           50%           75%           max  
average_rating      3.770000e+00  3.960000e+00  4.140000e+00  5.000000e+00  
isbn13              9.780350e+12  9.780570e+12  9.780870e+12  9.789880e+12  
num_pages           2.000000e+02  3.040000e+02  4.165000e+02  3.342000e+03  
ratings_count       1.050000e+02  7.915000e+02  5.348750e+03  2.457092e+06  
text_reviews_count  9.000000e+00  4.900000e+01  2.490000e+02  5.584300e+04  
year                1.998000e+03  2.003000e+03  2.005000e+03  2.019000e+03

In [61]:
df_books[df_books['average_rating']>4]['title'].count()

2115

In [65]:
df_books.iloc[0:5,0:4]

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating        isbn13  
0                  Victor Hugo            4.00  9.780350e+12  
1  Lidia Matticchio Bastianich            4.14  9.780770e+12  
2             James Scott Bell            4.00  9.780310e+12  
3         David Foster Wallace            3.86  9.780350e+12  
4          Laurell K. Hamilton            4.13  9.780430e+12

In [78]:
df_books.loc[[1,4],['language_code','num_pages','ratings_count']]

language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [80]:
df_books['num_pages'].mean()

341.0940205355345

In [81]:
df_books['num_pages'].mode()

0    288.0
Name: num_pages, dtype: float64

In [82]:
df_books['num_pages'].median()

304.0

In [83]:
df_books['num_pages'].max()

3342.0

In [87]:
df_books.head(10)

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   
5       The Hand of Chaos (The Death Gate Cycle  #5)   
6                                    On Intelligence   
7                           The Summit (Everest  #3)   
8                                   Where I Was From   
9                            A Sentimental Education   

                        author  average_rating        isbn13 language_code  \
0                  Victor Hugo            4.00  9.780350e+12         en-US   
1  Lidia Matticchio Bastianich            4.14  9.780770e+12         en-GB   
2             James Scott Bell            4.00  9.780310e+12           eng   
3         David Foster Wallace            3.86  9.780350e+12           eng   
4          Laurell K. Hamilton            4.13  9.780430e+12         en-US   
5                Margaret Weis            4.06  9.780550e+12           eng   
6                 Jeff Hawkins            4.12  9.780810e+12           eng   
7                Gordon Korman            3.96  9.780440e+12           eng   
8                  Joan Didion            3.86  9.780680e+12           eng   
9             Gustave Flaubert            3.83  9.780190e+12           eng   

   num_pages  ratings_count  text_reviews_count                publisher  year  
0      534.0            140                  22           Modern Library  2004  
1      288.0             48                   3          Clarkson Potter  2003  
2      345.0            368                  36                Zondervan  2004  
3      273.0          18335                1155                   Abacus  2000  
4      368.0          59524                 946        Berkley Hardcover  2006  
5      446.0          16301                 117                  Spectra  1993  
6      261.0           5347                 396     St. Martin's Griffin  2005  
7      154.0           2584                 106    Scholastic Paperbacks  2002  
8      240.0           2842                 292                  Vintage  2004  
9      464.0            105                   7  Oxford University Press  2000

In [92]:
df_books[df_books["year"]==2010]["title"].count()

15

In [95]:
df_books[(df_books["publisher"]=='DAW')&(df_books["average_rating"]>4)]

title           author  \
71                           By the Sword (Valdemar)  Mercedes Lackey   
871         Storm Rising (Valdemar: Mage Storms  #2)  Mercedes Lackey   
1523       Phoenix and Ashes (Elemental Masters  #3)  Mercedes Lackey   
1583  To Battle the Gods (Jalav  Amazon Warrior  #5)     Sharon Green   
3726        Oathblood (Valdemar: Vows and Honor  #3)  Mercedes Lackey   
4367                     Joust (Dragon Jousters  #1)  Mercedes Lackey   

      average_rating        isbn13 language_code  num_pages  ratings_count  \
71              4.25  9.780890e+12           eng      492.0          18531   
871             4.02  9.780890e+12         en-US      412.0          10781   
1523            4.01  9.780760e+12           eng      480.0           6980   
1583            4.07  9.780890e+12           eng      446.0             87   
3726            4.06  9.780890e+12         en-GB      394.0           9786   
4367            4.02  9.780760e+12           eng      448.0          10113   

      text_reviews_count publisher  year  
71                   249       DAW  1991  
871                   86       DAW  1996  
1523                 229       DAW  2005  
1583                   1       DAW  1986  
3726                 103       DAW  1998  
4367                 263       DAW  2004

In [97]:
df_books[(df_books["num_pages"]>500)&(df_books["year"]>2010)]["title"].count()

5

In [98]:
df_books[(df_books["language_code"]=="spa")&(df_books["year"]>2000)]["title"].count()

84

In [103]:
df_books[df_books["author"]== "Agatha Christie"]["title"].count()

21

In [107]:
df_books[df_books["language_code"]=="eng"]

title                author  \
2                                Breach of Promise      James Scott Bell   
3                Brief Interviews with Hideous Men  David Foster Wallace   
5     The Hand of Chaos (The Death Gate Cycle  #5)         Margaret Weis   
6                                  On Intelligence          Jeff Hawkins   
7                         The Summit (Everest  #3)         Gordon Korman   
...                                            ...                   ...   
4994                               How to Be Alone      Jonathan Franzen   
4995                            The Complete Works   Michel de Montaigne   
4996                          Shipwreck (Island I)         Gordon Korman   
4997      Every Night Italian: Every Night Italian        Giuliano Hazan   
4998                                Go Down  Moses      William Faulkner   

      average_rating        isbn13 language_code  num_pages  ratings_count  \
2               4.00  9.780310e+12           eng      345.0            368   
3               3.86  9.780350e+12           eng      273.0          18335   
5               4.06  9.780550e+12           eng      446.0          16301   
6               4.12  9.780810e+12           eng      261.0           5347   
7               3.96  9.780440e+12           eng      154.0           2584   
...              ...           ...           ...        ...            ...   
4994            3.59  9.780010e+12           eng      306.0            336   
4995            4.44  9.781400e+12           eng     1392.0            166   
4996            3.80  9.780440e+12           eng        NaN            103   
4997            3.79  9.780680e+12           eng      256.0             70   
4998            3.93  9.780680e+12           eng      365.0           8289   

      text_reviews_count               publisher  year  
2                     36               Zondervan  2004  
3                   1155                  Abacus  2000  
5                    117                 Spectra  1993  
6                    396    St. Martin's Griffin  2005  
7                    106   Scholastic Paperbacks  2002  
...                  ...                     ...   ...  
4994                  33        Harper Perennial  2007  
4995                  13      Everyman's Library  2003  
4996                  14  Scholastic Audio Books  2007  
4997                   2                Scribner  2000  
4998                 370                 Vintage  1991  

[3990 rows x 10 columns]

In [108]:
df_books[df_books["language_code"]=="eng"]["average_rating"].mean()

3.931142857142865

In [109]:
df_books.groupby("language_code")[["average_rating"]].mean()

average_rating
language_code                
en-GB                3.922523
en-US                3.914800
eng                  3.931143
ger                  3.979773
grc                  2.366667
jpn                  4.252381
lat                  4.170000
mul                  4.116000
spa                  3.927938